{% set build = 0 %}

package:
  name: periortree
  version: '0.0.1'

source:
  - path: ../include
    folder: include
  - path: ../periortree
    folder: periortree
  - path: ../README.md
  - path: ../LICENSE
  - path: ../pyproject.toml
  - path: ../setup.py

build:
  number: {{ build }}
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - boost
    - cppyy
    - numpy

test:
  commands:
    - python -m periortree.test

about:
  home: 'https://github.com/lasergyro/periortree'
  license: 'MIT'
  license_file: '{{ environ["SRC_DIR"] }}/LICENSE'
  summary: 'An extension of R-Tree1 for Periodic Boundary Condition.'
  description: |
    An extension of R-Tree[1](#References) for Periodic Boundary Condition.
    PerioR-Tree is a header-only library depending on Boost C++ Library.
    This fork packages it for python via conda and a minimal interface using cppyy.

extra:
  recipe-maintainers:
   -  lasergyro
